name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: news-app-apk
          path: build/app/outputs/flutter-apk/*.apk
